name: Sentry Release

on:
  release:
    types: [published]

jobs:
  sentry-release:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Create Sentry Release for LiC
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: "production"
          version: ${{ github.ref }}
          version_prefix: "v"
